sudo: required
services:
  - docker
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install jq
  - sudo apt-get install -y libffi-dev
#  - sudo apt-get install gcc
#  - sudo apt-get install -y python-cffi
  - sudo apt-get install -y libffi6
#  - sudo apt-get install -y cffi
  - sudo apt-get install python-tk
#  - sudo apt-get install -y openssl-dev
#  - chmod u+x builds.sh
  - chmod u+x build.sh
  - chmod u+x create_hassio_addon.sh
#  - sudo echo "http://dl-cdn.alpinelinux.org/alpine/v3.6/community" >> /etc/apk/repositories 
#  - sudo echo "http://dl-cdn.alpinelinux.org/alpine/v3.6/main" >> /etc/apk/repositories  
#  - sudo echo "ipv6" >> /etc/modules
#  - sudo echo "http://dl-1.alpinelinux.org/alpine/v3.6/main" >> /etc/apk/repositories; \
#  - sudo echo "http://dl-2.alpinelinux.org/alpine/v3.6/main" >> /etc/apk/repositories; \
#  - sudo echo "http://dl-3.alpinelinux.org/alpine/v3.6/main" >> /etc/apk/repositories; \
#  - sudo echo "http://dl-4.alpinelinux.org/alpine/v3.6/main" >> /etc/apk/repositories; \
#  - sudo echo "http://dl-5.alpinelinux.org/alpine/v3.6/main" >> /etc/apk/repositories
env:
#  - ADDON=appdaemon ARCH=armhf
#  - ADDON=appdaemon ARCH=aarch64
#  - ADDON=appdaemon ARCH=amd64
#  - ADDON=appdaemon ARCH=i386
  - ADDON=appdaemon
script:
  - docker login -u "$DOCKER_USER" -p "$DOCKER_PASS"
#  - ./builds.sh "$ADDON" "$ARCH"
  - ./build.sh "$ADDON"
after_success:
#  - if [ "$TRAVIS_BRANCH" == "master" ]; then
#    docker login -u="$DOCKER_USER" -p="$DOCKER_PASS";
#    docker push docker.io/sparck75/armhf-addon-appdaemon;
#    docker push docker.io/sparck75/amd64-addon-appdaemon;
#    docker push docker.io/sparck75/i386-addon-appdaemon;
#    docker push docker.io/sparck75/aarch64-addon-appdaemon;
#    fi
