sudo: required
services:
  - docker
before_install:
  - sudo apt-get install jq
env:
  - ADDON=appdaemon ARCH=armhf
  - ADDON=appdaemon ARCH=aarch64
  - ADDON=appdaemon ARCH=amd64
  - ADDON=appdaemon ARCH=i386
script:
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
  - ./builds.sh "$ADDON" "$ARCH"
