sudo: required
services:
  - docker
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install jq
  - sudo apt-get install -y python-cffi
  - sudo apt-get install -y python3-cffi
#  - chmod u+x builds.sh
  - chmod u+x build.sh
  - chmod u+x create_hassio_addon.sh
env:
#  - ADDON=appdaemon ARCH=armhf
#  - ADDON=appdaemon ARCH=aarch64
#  - ADDON=appdaemon ARCH=amd64
#  - ADDON=appdaemon ARCH=i386
  - ADDON=appdaemon
script:
  - docker login -u "$DOCKER_USER" -p "$DOCKER_PASS"
#  - ./builds.sh "$ADDON" "$ARCH"
  - ./build.sh "$ADDON"
after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u="$DOCKER_USER" -p="$DOCKER_PASS";
    docker push sparck75/ha-addons;
    fi
